various changes

diff --git a/helper/bin/wrappers/python b/helper/bin/wrappers/python
--- a/helper/bin/wrappers/python
+++ b/helper/bin/wrappers/python
@@ -1,89 +1,124 @@
 #!/bin/bash
 
-echo Running a python wrapper...
+[ -n "${DEBUG:-}" ] && echo Running a python wrapper...
 
-# Ensure container module was loaded ---
 if [ -z "$SING_IMAGE" ]; then
     echo "ERROR: No singularity-based module loaded!"
     THIS_DIR=$(dirname "$(readlink -f "$0")")
-    echo "You probably should not have $THIS_DIR in your PATH."
+    echo "You probably should not have $THIS_DIR in your PATH." >&2
     exit 1
 fi
 
-REAL_PYTHON="${BASH_SOURCE[0]}"
-echo ===================================================================================
-echo " Real python              : $REAL_PYTHON"
-EXEC_BIN=$(basename "$0")
-echo " Running binary           : $EXEC_BIN"
-echo " Container                : $SING_IMAGE"
+THIS="${BASH_SOURCE[0]}"   # THIS is the wrapper file path (argv0 label to show in ps/top).
+BASENAME=$(basename "$0")  # BASENAME becomes the name you invoked the wrapper as (e.g. python, pip).
+THISDIR=$(cd -P -- "$(dirname -- "$THIS")" && pwd) || { echo "cannot resolve THISDIR" >&2; return 1 2>/dev/null || exit 1; }
+BASEDIR=$(cd -P -- "$THISDIR/../.." && pwd)        || { echo "cannot resolve BASE" >&2; is_sourced && return 1 || exit 1; }
+VENV_DIR="$THISDIR/../../venv"
 
-export SING_FLAGS="$SING_FLAGS -B /appl/local/csc/soft/ai/bin -B /appl/lumi"
+if [ "$BASENAME" = "sing-bash" ]; then
+    BASENAME="bash"
+fi
+if [ "$BASENAME" != "bash" ]; then
+    if [ -n "${VIRTUAL_ENV:-}" ]; then
+	for d in "$VIRTUAL_ENV"/lib/python*/site-packages \
+		 "$VIRTUAL_ENV"/lib64/python*/site-packages; do
+	    [ -d "$d" ] && PYTHONPATH="${d}${PYTHONPATH:+:$PYTHONPATH}"
+	done
+	[ -n "${DEBUG:-}" ] && echo "Lifted the virtual environment to PYTHONPATH"
+	export PYTHONPATH
+    else
+	# 1) If no venv active, try to activate ../venv
+	if [ -z "${VIRTUAL_ENV:-}" ] &&
+	   [ -r "$VENV_DIR/bin/activate" ]; then
+	    # shellcheck disable=SC1091
+	    . "$VENV_DIR/bin/activate"
+	    [ -n "${DEBUG:-}" ] && echo "Temporarily activated the default virtual environment"
+	fi    
+	# 2) If still no venv active, fall back to adding
+	#    its site-packages to PYTHONPATH (silent)
+	if [ -z "${VIRTUAL_ENV:-}" ]; then
+	    
+	    if [ -r "$VENV_DIR/lib" ] ||
+	       [ -r "$VENV_DIR/lib64" ]; then
+		for d in "$VENV_DIR"/lib/python*/site-packages \
+			 "$VENV_DIR"/lib64/python*/site-packages; do
+		    [ -d "$d" ] || continue
+		PYTHONPATH="${d}${PYTHONPATH:+:$PYTHONPATH}"
+		[ -n "${DEBUG:-}" ] && echo "Temporarily included the default environment"
+		done
+		export PYTHONPATH
+	    else
+		[ -n "${DEBUG:-}" ] && echo "No active or default venv found"
+	    fi
+	fi
+    fi
+fi
 
+# In module: setenv('SING_FLAGS', '-B /bin/ip:/bin/ip 
+#   -B /usr/lib64/libmnl.so.0:/usr/lib64/libmnl.so.0 
+#   -B /opt/cray/libfabric/1.15.2.0/bin/fi_info:/bin/fi_info 
+#   -B /usr/lib64/libcurl.so.4:/usr/lib/libcurl.so.4')
+#
+# SING_FLAGS="$SING_FLAGS -B /opt/cray"
+# SING_FLAGS="$SING_FLAGS -B /pfs:/pfs"
+# SING_FLAGS="$SING_FLAGS -B /scratch:/scratch"
+# SING_FLAGS="$SING_FLAGS -B /projappl:/projappl"
+# SING_FLAGS="$SING_FLAGS -B /project:/project"
+# SING_FLAGS="$SING_FLAGS -B /flash:/flash"
+SING_FLAGS="$SING_FLAGS -B /users:/users"
+SING_FLAGS="$SING_FLAGS -B /appl/local/csc/soft/ai/bin"
+SING_FLAGS="$SING_FLAGS -B /appl/lumi"
+if [ -d "$TMPDIR" ]; then
+    SING_FLAGS="$SING_FLAGS -B $TMPDIR:$TMPDIR"
+fi
 # This is needed for commands line lumi-allocations to work, but this path is not present in compute nodes
 if [ -d "/var/lib/project_info" ]; then
     SING_FLAGS="$SING_FLAGS -B /var/lib/project_info"
-    echo SING_FLAGS=$SING_FLAGS
 fi
+export SING_FLAGS
 
-# Virtualenv PYTHONPATH helper (only needed inside container) 
-echo " Virtual environment      : $VIRTUAL_ENV"
-if [ -n "$VIRTUAL_ENV" ]; then
-    for _tmp_py_dir in "$VIRTUAL_ENV"/lib{,64}/python*/site-packages; do
-	echo " - included directory     : $_tmp_py_dir"
-        export PYTHONPATH="$_tmp_py_dir:$PYTHONPATH"
-    done
-fi
-
-# echo "Crucial environment variables..."
-# env | egrep '^(RCCL|FI_|NCCL_|PLUGIN|LD_LIB|HSA_|WITH_CONDA|CXI_|SLURM_|MIOPEN_)'
+rmprefix() {
+  base=${1%/}
+  path=$2
+  [ -z "$base" ] && { printf '%s\n' "$path"; return; }
+  if [ "$base" = "/" ]; then
+    [ "$path" = "/" ] && { printf '.\n'; return; }
+    printf '%s\n' "${path#/}"
+    return
+  fi
+  case $path in
+    "$base")    printf '.\n' ;;
+    "$base"/*)  printf '%s\n' "${path#"$base"/}" ;;
+    *)          printf '%s\n' "$path" ;;
+  esac
+  return
+}
+SING_SHORT=$(rmprefix "$BASEDIR" "$SING_IMAGE")
+REAL_SHORT=$(rmprefix "$BASEDIR" "$THIS")
+[ -n "${DEBUG:-}" ] && echo "==================================================================================="
+[ -n "${DEBUG:-}" ] && echo " \$HELPER                  : $BASEDIR"
+[ -n "${DEBUG:-}" ] && echo " Real binary              : \$HELPER/$REAL_SHORT"
+[ -n "${DEBUG:-}" ] && echo " SING_IMAGE               : \$HELPER/$SING_SHORT"
+[ -n "${DEBUG:-}" ] && printf '%s\n' " $SING_FLAGS" \
+	| sed -E ' s/[[:space:]]+-/\n SING_FLAGS                 -/g' | sed '/^$/d' 
+[ "$BASENAME" != "bash" ] && [ -n "${DEBUG:-}" ] && echo " VIRTUAL_ENV              : $VIRTUAL_ENV"
+[ "$BASENAME" != "bash" ] && [ -n "${DEBUG:-}" ] && printf '%s\n' ":$PYTHONPATH" \
+	| sed -E ' s/:/\n PYTHONPATH               : /g' | sed '/^$/d' | sed '/^ PYTHONPATH *: *$/d' 
+[ -n "${DEBUG:-}" ] && echo " Running binary           : $BASENAME"
+[ -n "${DEBUG:-}" ] && echo " Command-Line Arguments   :" "$@"
+[ -n "${DEBUG:-}" ] && echo "==================================================================================="
 
 if [ -d /.singularity.d/ ]; then
-    echo We are already in the container
-
-    if [ -n "$WITH_CONDA" ]; then
-        eval "$WITH_CONDA"
-    else
-        echo "⚠️  WITH_CONDA not set — using default container Python."
-    fi
-
-#    if [ -d "$PROJHOME/venv/mammoth3.10-with-site" ]; then
-#        source "$PROJHOME/venv/mammoth3.10-with-site/bin/activate"
-#    else
-#        echo "⚠️  Virtualenv not found at $PROJHOME/venv/mammoth3.10-with-site"
-#    fi
-
-    # Finally, run the intended command
-    echo exec -a $REAL_PYTHON $EXEC_BIN "$@"
-    exec -a $REAL_PYTHON $EXEC_BIN "$@"
-
+    exec -a "$BASENAME" "$@"
 else
-    # echo Launch into container and forward virtual environment
-    CONTAINER_CMD=""
-
-    # Build container-side command to run after entry
-    if [ -n "$WITH_CONDA" ]; then
-        CONTAINER_CMD="\$WITH_CONDA && "
-    fi
-
-#    if [ "$VIRTUAL_ENV" != "$PROJHOME/venv/mammoth3.10-with-site" ]; then
-#       CONTAINER_CMD+="source $PROJHOME/venv/mammoth3.10-with-site/bin/activate && "
-#    fi
-    
-    CONTAINER_CMD+="exec -a \"$REAL_PYTHON\" \"$EXEC_BIN\""
-    if [ $# -gt 0 ]; then
-        CONTAINER_CMD+=" $(printf " %q" "$@")"
-    fi
-
-    BINDINGS="--bind /bin/ip:/bin/ip --bind /usr/lib64/libmnl.so.0:/usr/lib64/libmnl.so.0 \
-    --bind /opt/cray/libfabric/1.15.2.0/bin/fi_info:/bin/fi_info --bind /sys:/sys:ro "
-
-    echo " Running binary           : $EXEC_BIN"
-    echo " Binding                  : $BINDINGS"
-    printf '%s\n' "  $BINDINGS" \
-	| sed -E ' s/[[:space:]]+--bind/\n Binding                  :/g' | sed '/^$/d' 
-    echo " Command                  : $CONTAINER_CMD"
-    echo ===================================================================================
-    #    /appl/local/csc/soft/ai/bin/singularity_wrapper
-    
-    singularity exec $BINDINGS $SING_IMAGE bash -c "$CONTAINER_CMD"
+    singularity exec \
+		--env LD_LIBRARY_PATH="$BASEDIR/lib:\$LD_LIBRARY_PATH" \
+		$SING_FLAGS $SING_IMAGE \
+		"$BASENAME" "$@"
+    # --env LD_LIBRARY_PATH="$BASEDIR/lib:$LD_LIBRARY_PATH" expands
+    # the host $LD_LIBRARY_PATH before entering the container, then
+    # sets that literal inside. If you meant “prepend and keep the
+    # container’s current value”, you must escape the $ so it expands
+    # inside the container.
+    exit $?
 fi
